### ISSUE TITLE
File below minimum sizes ends execution early

### ISSUE THREAD

**Issue by pingzing** [kurtmckee/pelican_precompress#5]
Exactly what it says on the tin. It's a super-simple fix, too: on [line 151](https://github.com/kurtmckee/pelican_precompress/blob/bfa12d21b01f3ea8f7b150f507559570c1dd9ffe/pelican_precompress.py#L151), change the `return` to a `continue`. I'd open a PR for this, but honestly, this seems like it'd be less work for all involved ;)

**Comment by kurtmckee** [comment]
Well...that's super dumb behavior, haha!

I'll push a release shortly to fix this problem. Thank you very much for reporting this issue!

**Comment by kurtmckee** [comment]
Neil, version 1.1.2 is released with a fix. Thanks again for reporting this!
