### ISSUE TITLE
Path to static files in theme

### ISSUE THREAD

**Issue by johnmathews** [kurtmckee/pelican_precompress#6]
Hey! Nice plugin! The content is being compressed, but the themes static files are not. Is there a way to specify paths?

**Comment by johnmathews** [comment]
my bad.

**Comment by kurtmckee** [comment]
Thanks John! I see that you already closed the ticket, but what was happening? Was it skipping images and fonts?

Please let me know what you were seeing. Perhaps the plugin documentation can be improved. =)
